#! /usr/bin/python3

import sys
import getopt
from statusjira import jiraproject as JP
from statusjira import projectxml as PX
from statusjira import appglobal as AG



if __name__ == '__main__':

            
    print ('PROGNAME: ' , AG.args.PROGNAME)
    
#    projectfile = PX.file()
#    projectfile.load(args[0]) # input argument is the file to be processed

#    listoftickets = projectfile.findalltickets()

#    project = JP.project()
#    project.createepics(projectfile.findalltickets())

        
#    print (project.csv())



