#! /usr/bin/python3

import sys
from statusjira import jiraproject as JP
from statusjira import projectxml as PX
from statusjira import jiraticket as JT
from statusjira import appglobal as AG



if __name__ == '__main__':

            
    #print (AG.ARGS)

    # If erorrtext is "Not None" then there was a command line parsing error
    # Display the error and help text then exit
    if (AG.ARGS.errortext()):
        print (AG.ARGS.errortext())
        print ()
        print (AG.ARGS.helptext())
        sys.exit(2)
    
    # Input arguments are valid, proceed with processing the input file
    projectfile = PX.file()
    projectfile.load(AG.ARGS.infilename()) # input argument is the file to be processed

    listoftickets = projectfile.findalltickets()

    project = JP.project()
    project.createepics(projectfile.findalltickets())

    if (AG.ARGS.outfmtcsv()):
        print (project.csv())
    elif (AG.ARGS.outfmthtml()):
        print (project.html())
    else:
        
        jiraticket = JT.ticket(listoftickets[0])

        print ("Ticket, Epic, Assignee, Team, Type, Status, Pct, Summary")

        for tktdata in listoftickets:
            jiraticket.reinit(tktdata)
            print (jiraticket)



